include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/src/generated
    - lib/src/models/*.g.dart

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
