name: open_meteo_api
description: A new Flutter package project.
version: 0.0.1
homepage: 'holder'

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.7.0
  protobuf: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  lints: ^2.0.1
  mockito: ^5.3.2
  test: ^1.22.0

